### ISSUE TITLE
[Feature Request] - Bump without install

### ISSUE THREAD

**Issue by jaysc** [JonShort/npm-bumpall#10]
To get any results using the program, you have to install the node packages first. We should be able to bump without installing anything.

**Comment by JonShort** [comment]
Nice find - hopefully it's just handling the `MISSING` output and installing the package at requested version

<img width="458" alt="image" src="https://user-images.githubusercontent.com/21317379/206793695-e6e6c93e-cbc8-4814-afe8-dfcbfb23ee68.png">

I can work on this tomorrow unless you fancy it?

**Comment by jaysc** [comment]
@JonShort I'd like to handle it please.
