### ISSUE TITLE
[Enhancement] - add help argument

### ISSUE THREAD

**Issue by JonShort** [JonShort/npm-bumpall#17]
Most CLI tools have a "help mode" which prints out the available args / commands

Something like this should exist for bumpall

E.g.
`bumpall help`

...all available args printed with information

We do need to decide whether to have this as a flag (`--help | -h`) or an argument (see e.g. above)

Flag is consistent and probably easier to implement so that might be the best first step

**Comment by jaysc** [comment]
i think at this point we should just switch to a package.

This is the one I used before: https://docs.rs/clap/latest/clap/

**Comment by JonShort** [comment]
Agree - probably worth it now there's so many flags
